api = "0.2"

[buildpack]
id = "tech.monstrs.buildpacks.yarn-static-workspace"
version = "0.0.3"
name = "Yarn Static Workspace Buildpack"

[metadata]
include_files = ["buildpack.toml"]

[[order]]

[[order.group]]
id = "tech.monstrs.buildpacks.yarn-install"
version = "0.0.3"

[[order.group]]
id = "tech.monstrs.buildpacks.yarn-workspace-build"
version = "0.0.3"

[[order.group]]
id = "tech.monstrs.buildpacks.yarn-workspace-serve"
version = "0.0.3"
